### ISSUE TITLE
Strona główna z przykładowymi daniami, około 7, jakiś domyślny filter(np. pasta), możliwość zmiany filtra na coś innego (user imput)

### ISSUE THREAD

**Issue by radekwojpl2** [radekwojpl2/CodersCamp2020.CookBook#4]

**Comment by Yoruko90** [comment]
# Requirements
Site should have two sections
1. Search section
 - some filter (e.g. cuisine: italian) which can be deactivated (it could be a button or a checkbox)
-  field with text input
- search button (click will load recipies from API with selected filters)
 2. Recipes section with 7 recipes
 3. Each recipe should have: 
  - photo
  - ingredients list
  - instruction



# Example
![mainpage](https://user-images.githubusercontent.com/74741825/103466700-766ffe80-4d47-11eb-9f62-02b7a9d50294.png)

# To do 
 - [ ] Search section
 - [ ] Recipes section with 7 recipes
 - [ ] Recipe design
