### ISSUE TITLE
Strona z randomowym daniem, przycisk na pobranie nowego oraz przycisk na pobieranie nowego dania cały czas interwał co 10s

### ISSUE THREAD

**Issue by radekwojpl2** [radekwojpl2/CodersCamp2020.CookBook#5]

**Comment by MaDud** [comment]
#Requirements

Card should contain two sections:
1. Button section (two separate buttons or one shared)
 - button to generate new random recipe
 - button to generate new recipes in interval (interval can be set as default or there can be an input to let user set time)
2. Recipe section
 - photo
 - ingredients list
 - instruction

#Checklist
-[ ] button to generate random recipe
-[ ] button to generate recipes in interval
-[ ] recipe section with generated data 

![Blue and White Workplace Guidelines Coronavirus Poster](https://user-images.githubusercontent.com/48692842/103242004-1cd98f80-4955-11eb-8bce-5071186ee89f.jpg)
