### ISSUE TITLE
Gra w ile wartości odżywczych jest w danym produkcie, możliwość błędu +- jakaś wartość

### ISSUE THREAD

**Issue by radekwojpl2** [radekwojpl2/CodersCamp2020.CookBook#6]

**Comment by MaDud** [comment]
# Requirements
1.  On page should be one photo of dish to guess 
2.  The puzzle should conatin:
 - photo of dish
 - question with name of dish
 - input field with button to check answer
 - answer should be check as value between max and min
 - feedback after click button to check answer ( if correct info or background change color for green, if wrong - for red)

# Example

![Game](https://user-images.githubusercontent.com/48692842/103446009-009e6100-4c7b-11eb-9fe8-4f4e8920ce4b.jpg)

# To do 
 - [ ] get information about product from API
 - [ ] create HTML in JS for that product
 - [ ] send request to check answer
