### ISSUE TITLE
Lista zakupów, po wyjściu ze strony nie musi to być nigdzie zapisane, ewntualnie sesja, ciasteczka

### ISSUE THREAD

**Issue by radekwojpl2** [radekwojpl2/CodersCamp2020.CookBook#7]

**Comment by MaDud** [comment]
# Requirements

This card should contain of:
1. input with search button
2. table generated basing on results of search (list of products we can add to shopping list)
3. every product in table should have button to add it to shopping list
4. shopping list with added product


# Example
![ShoppingList (1)](https://user-images.githubusercontent.com/48692842/103446273-0f3a4780-4c7e-11eb-9610-2d4d59caf667.jpg)

# To do
 - [ ] input with search button
 - [ ] send request to search for products
 - [ ] generate table basing on search results with add buttons
 - [ ] add product to shopping list after click add button
