### ISSUE TITLE
Kalkulator na przeliczanie miar gramy na kilogramy i takie tam.

### ISSUE THREAD

**Issue by radekwojpl2** [radekwojpl2/CodersCamp2020.CookBook#8]

**Comment by Yoruko90** [comment]
Please check it :)  @radekwojpl2 @MaDud 

# Requirements

Card should contain :
1. Labels ( Value to Convert, From , To)
2. Text input ( number )
3. Two select button with kilograms, grams etc
4. Button clear  (button to clear input )
5. Button Calculate (button to generate converted value)
6. Div with answer

![calculator](https://user-images.githubusercontent.com/74741825/103385501-066d3880-4afb-11eb-8147-6b440d69764b.jpg)

# Checklist
- [ ] Labels
- [ ] Text input
- [ ] Two select button 
- [ ] Button clear
- [ ] Button Calculate
- [ ] Div with answer
